source 'https://github.com/CocoaPods/Specs.git'

target 'TLMetaResolver', :exclusive => true do
  pod "TLMetaResolver", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TLMetaResolver", :path => "../"

  
end
